apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: traepis-development-ingress-controller

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traepis-development-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traepis-development-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traepis-development-ingress-controller
  template:
    metadata:
      labels:
        k8s-app: traepis-development-ingress-controller
        name: traepis-development-ingress-controller
    spec:
      serviceAccountName: traepis-development-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik
        args:
        - --api
        - --kubernetes
        - --kubernetes.labelSelector=ingress-controller=traepis-development
        - "--entryPoints=Name:http Address::80"
        - "--entryPoints=Name:traefik Address::6001"
        ports:
        - containerPort: 80
        - containerPort: 6001
