apiVersion: v1
kind: PersistentVolume
metadata:
  name: traepis-development-code
  namespace: traepis-development
  labels:
    name: traepis-development-code
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /Users/<your user name>/Code/traepis
    # should reside in the default mounted host folders as per
    # https://kubernetes.io/docs/getting-started-guides/minikube/#mounted-host-folders
    # otherwise you'll have to maintain a mounted folder on your own via minikube mount
  capacity:
    storage: 2Gi
  storageClassName: standard
